qemu.cmake: disable SDL image
This causes errors on our macOS CI:

_deps/libqemu-src/include/ui/sdl2.h:21:10: fatal error: 'SDL_image.h' file not found
                                                        ^~~~~~~~~~~~~
1 error generated.

And SDL is not really necessary. As Antonio put it "that's only needed
to load the png qemu image icon".

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>