Hexagon: libqemu/v8.1 fixes for Y6_dmlink
If pc has to be restored during an instruction (like it is currently
happening with Y6_dmlink during QNN runs), we need to also restore
memop_pc.set, otherwise a subsequent setting of memop_pc will abort.
This fixes an error in QNN:

ERROR: trying to set memop pc at file 'target/hexagon/helper_funcs_generated.c.inc' line 5155
but it was already set from 'target/hexagon/helper_funcs_generated.c.inc' line 5155.

Also add Y6_dmlink to the list of instructions that may do IO.

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>