Add missing includes, format
These #include's were missing and without them would result in warnings
or errors like the ones below:

    tests/tcg/hexagon/system/util.h:37:19: error: unknown type name 'uint64_t'
    tests/tcg/hexagon/system/vtcm_common.h:40:5: warning: call to undeclared function 'add_translation_fixed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    tests/tcg/hexagon/system/dma.h:71:5: warning: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    tests/tcg/hexagon/system/dma.h:60:5: warning: call to undeclared library function 'memset' with type 'void *(void *, int, unsigned int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    tests/tcg/hexagon/system/cfgtable.h:36:8: error: unknown type name 'uintptr_t'

Also: apply clang-format on these files.

Signed-off-by: Brian Cain <bcain@quicinc.com>