Reapply "libqemu: abort if gdb port is unavailable""
This reverts commit 3f0f468c2c070aa327c7bd35ea2deba66339ba3d,
effectively reapplying 7dba7705ed24255b0c451af72d87666e78b2a7d4.

The commit was previously reverted due to this error on mac:

  libqemu/exports/iothread-wrapper.c:329:5: error: implicit declaration
  of function 'libqemu_gdbserver_start'
      libqemu_gdbserver_start(params->p0);
      ^

The solution was to include this line in libqemu/exports.py:

  PrivateInclude('libqemu/wrappers/gdbserver.h')

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>