Fix signature of libqemu_cpu_unhalted_async_job
When building QQVP with clang 16.0.0, we see the compilation error
below.  So we'll change the signature of libqemu_cpu_unhalted_async_job()
to match run_on_cpu_func.

    ../../../../libqemu-src/libqemu/wrappers/cpu.c:132:31: error: incompatible function pointer types passing 'void (Object *)' (aka 'void (struct Object *)') to parameter of type 'run_on_cpu_func' (aka 'void (*)(struct CPUState *, run_on_cpu_data)') [-Wincompatible-function-pointer-types]
            async_run_on_cpu(cpu, libqemu_cpu_unhalted_async_job, RUN_ON_CPU_NULL);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /local/mnt/workspace/vp/qqvp/build_dbg/_deps/libqemu-src/include/hw/core/cpu.h:768:54: note: passing argument to parameter 'func' here
    void async_run_on_cpu(CPUState *cpu, run_on_cpu_func func, run_on_cpu_data data);
                                                         ^

Signed-off-by: Brian Cain <bcain@quicinc.com>