Fix un-named parameter for libqemu_cpu_unhalted_async_job
In da01404c7297d1eea35fc542a7cbe0436879b48e the signature was
changed to fix a compilation warning (-Wincompatible-function-pointer-types),
but this change introduced an error about an omitted parameter name:

    ../../../../../../override_repo/libqemu/wrappers/cpu.c:110:82: error: parameter name omitted
    static void libqemu_cpu_unhalted_async_job(struct CPUState *cpu_, run_on_cpu_data)
                                                                                     ^
    1 error generated.

Signed-off-by: Brian Cain <bcain@quicinc.com>